# Generated by Django 5.2.17 on 2026-08-27 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('meta_title', models.CharField(blank=True, max_length=180, verbose_name='meta title')),
                ('meta_title_uz', models.CharField(blank=True, max_length=180, null=True, verbose_name='meta title')),
                ('meta_title_ru', models.CharField(blank=True, max_length=180, null=True, verbose_name='meta title')),
                ('meta_title_en', models.CharField(blank=True, max_length=180, null=True, verbose_name='meta title')),
                ('meta_description', models.CharField(blank=True, max_length=320, verbose_name='meta description')),
                ('meta_description_uz', models.CharField(blank=True, max_length=320, null=True, verbose_name='meta description')),
                ('meta_description_ru', models.CharField(blank=True, max_length=320, null=True, verbose_name='meta description')),
                ('meta_description_en', models.CharField(blank=True, max_length=320, null=True, verbose_name='meta description')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='og/', verbose_name='OG rasm')),
                ('title', models.CharField(max_length=200, verbose_name='nomi')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='nomi')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='nomi')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='nomi')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug')),
                ('slug_uz', models.SlugField(blank=True, max_length=220, null=True, unique=True, verbose_name='slug')),
                ('slug_ru', models.SlugField(blank=True, max_length=220, null=True, unique=True, verbose_name='slug')),
                ('slug_en', models.SlugField(blank=True, max_length=220, null=True, unique=True, verbose_name='slug')),
                ('image_before', models.ImageField(upload_to='cases/', verbose_name='oldin')),
                ('image_after', models.ImageField(upload_to='cases/', verbose_name='keyin')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='izoh')),
                ('caption_uz', models.CharField(blank=True, max_length=300, null=True, verbose_name='izoh')),
                ('caption_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='izoh')),
                ('caption_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='izoh')),
                ('treatment_summary', models.TextField(blank=True, verbose_name='davolash tavsifi')),
                ('treatment_summary_uz', models.TextField(blank=True, null=True, verbose_name='davolash tavsifi')),
                ('treatment_summary_ru', models.TextField(blank=True, null=True, verbose_name='davolash tavsifi')),
                ('treatment_summary_en', models.TextField(blank=True, null=True, verbose_name='davolash tavsifi')),
                ('duration_note', models.CharField(blank=True, max_length=120, verbose_name='davomiyligi')),
                ('duration_note_uz', models.CharField(blank=True, max_length=120, null=True, verbose_name='davomiyligi')),
                ('duration_note_ru', models.CharField(blank=True, max_length=120, null=True, verbose_name='davomiyligi')),
                ('duration_note_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='davomiyligi')),
                ('consent_on_file', models.BooleanField(default=False, verbose_name='bemor roziligi bor')),
                ('is_published', models.BooleanField(default=False, verbose_name='chop etilgan')),
                ('is_featured', models.BooleanField(default=False, verbose_name='bosh sahifada')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='tartib')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='team.doctor', verbose_name='shifokor')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='services.service', verbose_name='xizmat')),
            ],
            options={
                'verbose_name': 'Ish (before/after)',
                'verbose_name_plural': 'Ishlarimiz',
                'ordering': ['order', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('is_published', False), ('consent_on_file', True), _connector='OR'), name='case_published_requires_consent')],
            },
        ),
    ]
