# Generated by Django 5.2.17 on 2026-08-27 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email'), ('sms', 'SMS')], default='telegram', max_length=16, verbose_name='kanal')),
                ('template_key', models.CharField(max_length=64, verbose_name='shablon')),
                ('target', models.CharField(blank=True, max_length=128, verbose_name='qabul qiluvchi')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Navbatda'), ('sent', 'Yuborildi'), ('failed', 'Xato'), ('abandoned', 'Tashlab yuborildi')], db_index=True, default='pending', max_length=16, verbose_name='status')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='urinishlar')),
                ('last_error', models.TextField(blank=True, verbose_name='oxirgi xato')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='payload')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='yuborilgan')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='keyingi urinish')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Xabarnoma',
                'verbose_name_plural': 'Xabarnomalar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='notificatio_status_64d90d_idx')],
            },
        ),
    ]
