# Generated by Django 5.2.17 on 2026-08-27 05:57

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_extensions'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('meta_title', models.CharField(blank=True, max_length=180, verbose_name='meta title')),
                ('meta_title_uz', models.CharField(blank=True, max_length=180, null=True, verbose_name='meta title')),
                ('meta_title_ru', models.CharField(blank=True, max_length=180, null=True, verbose_name='meta title')),
                ('meta_title_en', models.CharField(blank=True, max_length=180, null=True, verbose_name='meta title')),
                ('meta_description', models.CharField(blank=True, max_length=320, verbose_name='meta description')),
                ('meta_description_uz', models.CharField(blank=True, max_length=320, null=True, verbose_name='meta description')),
                ('meta_description_ru', models.CharField(blank=True, max_length=320, null=True, verbose_name='meta description')),
                ('meta_description_en', models.CharField(blank=True, max_length=320, null=True, verbose_name='meta description')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='og/', verbose_name='OG rasm')),
                ('title', models.CharField(max_length=250, verbose_name='sarlavha')),
                ('title_uz', models.CharField(max_length=250, null=True, verbose_name='sarlavha')),
                ('title_ru', models.CharField(max_length=250, null=True, verbose_name='sarlavha')),
                ('title_en', models.CharField(max_length=250, null=True, verbose_name='sarlavha')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True, verbose_name='slug')),
                ('slug_uz', models.SlugField(blank=True, max_length=280, null=True, unique=True, verbose_name='slug')),
                ('slug_ru', models.SlugField(blank=True, max_length=280, null=True, unique=True, verbose_name='slug')),
                ('slug_en', models.SlugField(blank=True, max_length=280, null=True, unique=True, verbose_name='slug')),
                ('excerpt', models.CharField(blank=True, max_length=350, verbose_name='qisqa matn')),
                ('excerpt_uz', models.CharField(blank=True, max_length=350, null=True, verbose_name='qisqa matn')),
                ('excerpt_ru', models.CharField(blank=True, max_length=350, null=True, verbose_name='qisqa matn')),
                ('excerpt_en', models.CharField(blank=True, max_length=350, null=True, verbose_name='qisqa matn')),
                ('body', models.TextField(verbose_name='matn')),
                ('body_uz', models.TextField(null=True, verbose_name='matn')),
                ('body_ru', models.TextField(null=True, verbose_name='matn')),
                ('body_en', models.TextField(null=True, verbose_name='matn')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='muqova')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='chop etilgan')),
                ('is_published', models.BooleanField(default=False, verbose_name='chop etilgan')),
                ('reading_time', models.PositiveSmallIntegerField(default=1, verbose_name='oʻqish vaqti (daq)')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='team.doctor', verbose_name='muallif')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Blog',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['is_published', '-published_at'], name='blog_post_is_publ_9ad937_idx'), django.contrib.postgres.indexes.GinIndex(fields=['title', 'excerpt'], name='post_title_excerpt_trgm', opclasses=['gin_trgm_ops', 'gin_trgm_ops'])],
            },
        ),
    ]
