# Generated by Django 5.2.17 on 2026-08-27 05:58

import apps.appointments.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_extensions'),
        ('services', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.appointments.models.generate_code, editable=False, max_length=12, unique=True, verbose_name='kod')),
                ('cancel_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='bekor qilish tokeni')),
                ('patient_name', models.CharField(max_length=150, verbose_name='bemor ismi')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('comment', models.TextField(blank=True, verbose_name='izoh')),
                ('starts_at', models.DateTimeField(verbose_name='boshlanish')),
                ('ends_at', models.DateTimeField(verbose_name='tugash')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlangan'), ('cancelled_by_patient', 'Bemor bekor qildi'), ('cancelled_by_clinic', 'Klinika bekor qildi'), ('completed', 'Yakunlandi'), ('no_show', 'Kelmadi')], db_index=True, default='pending', max_length=32, verbose_name='status')),
                ('source', models.CharField(choices=[('web', 'Sayt'), ('phone', 'Telefon'), ('telegram', 'Telegram'), ('admin', 'Admin')], default='web', max_length=16, verbose_name='manba')),
                ('locale', models.CharField(default='uz', max_length=5, verbose_name='til')),
                ('consent_given_at', models.DateTimeField(blank=True, null=True, verbose_name='rozilik vaqti')),
                ('consent_text_version', models.CharField(blank=True, max_length=32, verbose_name='rozilik matni versiyasi')),
                ('ip_hash', models.CharField(blank=True, max_length=64, verbose_name='IP hash')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User-Agent')),
                ('reminder_24h_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='24s eslatma')),
                ('reminder_2h_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='2s eslatma')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='team.doctor', verbose_name='shifokor')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='services.service', verbose_name='xizmat')),
            ],
            options={
                'verbose_name': 'Qabul',
                'verbose_name_plural': 'Qabullar',
                'ordering': ['-starts_at'],
                'indexes': [models.Index(fields=['starts_at', 'status'], name='appointment_starts__1f6bcd_idx'), models.Index(fields=['doctor', 'starts_at'], name='appointment_doctor__60bd67_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='appointment_end_after_start'), django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('doctor__isnull', False), ('status__in', ('pending', 'confirmed'))), expressions=[('doctor', '='), (apps.appointments.models.TsTzRange('starts_at', 'ends_at', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&')], name='appointment_no_overlap_per_doctor')],
            },
        ),
    ]
