# Generated by Django 5.2.17 on 2026-08-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('services', '0003_alter_service_duration_minutes_and_more'),
        ('team', '0002_alter_doctorschedule_slot_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='idempotency_key',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='idempotency key'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reschedule_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='koʻchirishlar soni'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source', 'web'), _negated=True), models.Q(('doctor__isnull', False), ('service__isnull', False)), _connector='OR'), name='appointment_web_requires_doctor_and_service'),
        ),
    ]
