# Generated by Django 5.2.17 on 2026-08-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceitem',
            name='qualifier',
            field=models.CharField(blank=True, max_length=60, verbose_name='izoh'),
        ),
        migrations.AlterField(
            model_name='priceitem',
            name='qualifier_en',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='izoh'),
        ),
        migrations.AlterField(
            model_name='priceitem',
            name='qualifier_ru',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='izoh'),
        ),
        migrations.AlterField(
            model_name='priceitem',
            name='qualifier_uz',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='izoh'),
        ),
    ]
