# Generated by Django 5.2.17 on 2026-08-27 07:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_priceitem_qualifier_and_more'),
        ('team', '0002_alter_doctorschedule_slot_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5)], verbose_name='davomiyligi (daq)'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 5)), name='service_duration_min'),
        ),
    ]
