# Generated by Django 5.2.17 on 2026-08-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='brand/', verbose_name='hero rasmi'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='og/', verbose_name='OG rasm (default)'),
        ),
    ]
