# Generated by Django 5.2.17 on 2026-08-28 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_clinicsettings_hero_image_clinicsettings_og_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicsettings',
            name='accent_color',
            field=models.CharField(default='#F2A65A', max_length=9, validators=[django.core.validators.RegexValidator(message='Hex rang boʻlishi kerak: #RGB, #RGBA, #RRGGBB yoki #RRGGBBAA (masalan #0E7C86).', regex='^#(?:[0-9a-fA-F]{3,4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')], verbose_name='accent rang'),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='brand_color',
            field=models.CharField(default='#0E7C86', max_length=9, validators=[django.core.validators.RegexValidator(message='Hex rang boʻlishi kerak: #RGB, #RGBA, #RRGGBB yoki #RRGGBBAA (masalan #0E7C86).', regex='^#(?:[0-9a-fA-F]{3,4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')], verbose_name='brand rang'),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='ink_color',
            field=models.CharField(default='#0F172A', max_length=9, validators=[django.core.validators.RegexValidator(message='Hex rang boʻlishi kerak: #RGB, #RGBA, #RRGGBB yoki #RRGGBBAA (masalan #0E7C86).', regex='^#(?:[0-9a-fA-F]{3,4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')], verbose_name='matn rangi'),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='surface_color',
            field=models.CharField(default='#FFFFFF', max_length=9, validators=[django.core.validators.RegexValidator(message='Hex rang boʻlishi kerak: #RGB, #RGBA, #RRGGBB yoki #RRGGBBAA (masalan #0E7C86).', regex='^#(?:[0-9a-fA-F]{3,4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')], verbose_name='fon rangi'),
        ),
    ]
