# Generated by Django 5.2.17 on 2026-08-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('meta_title', models.CharField(blank=True, max_length=180, verbose_name='meta title')),
                ('meta_title_uz', models.CharField(blank=True, max_length=180, null=True, verbose_name='meta title')),
                ('meta_title_ru', models.CharField(blank=True, max_length=180, null=True, verbose_name='meta title')),
                ('meta_title_en', models.CharField(blank=True, max_length=180, null=True, verbose_name='meta title')),
                ('meta_description', models.CharField(blank=True, max_length=320, verbose_name='meta description')),
                ('meta_description_uz', models.CharField(blank=True, max_length=320, null=True, verbose_name='meta description')),
                ('meta_description_ru', models.CharField(blank=True, max_length=320, null=True, verbose_name='meta description')),
                ('meta_description_en', models.CharField(blank=True, max_length=320, null=True, verbose_name='meta description')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='og/', verbose_name='OG rasm')),
                ('key', models.CharField(choices=[('privacy', 'Maxfiylik siyosati'), ('offer', 'Ommaviy oferta'), ('terms', 'Foydalanish shartlari')], max_length=16, unique=True, verbose_name='kalit')),
                ('title', models.CharField(max_length=200, verbose_name='sarlavha')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='sarlavha')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='sarlavha')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='sarlavha')),
                ('body', models.TextField(verbose_name='matn')),
                ('body_uz', models.TextField(null=True, verbose_name='matn')),
                ('body_ru', models.TextField(null=True, verbose_name='matn')),
                ('body_en', models.TextField(null=True, verbose_name='matn')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
            ],
            options={
                'verbose_name': 'Statik sahifa',
                'verbose_name_plural': 'Statik sahifalar',
            },
        ),
    ]
