# Generated by Django 5.2.17 on 2026-08-27 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('meta_title', models.CharField(blank=True, max_length=180, verbose_name='meta title')),
                ('meta_title_uz', models.CharField(blank=True, max_length=180, null=True, verbose_name='meta title')),
                ('meta_title_ru', models.CharField(blank=True, max_length=180, null=True, verbose_name='meta title')),
                ('meta_title_en', models.CharField(blank=True, max_length=180, null=True, verbose_name='meta title')),
                ('meta_description', models.CharField(blank=True, max_length=320, verbose_name='meta description')),
                ('meta_description_uz', models.CharField(blank=True, max_length=320, null=True, verbose_name='meta description')),
                ('meta_description_ru', models.CharField(blank=True, max_length=320, null=True, verbose_name='meta description')),
                ('meta_description_en', models.CharField(blank=True, max_length=320, null=True, verbose_name='meta description')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='og/', verbose_name='OG rasm')),
                ('full_name', models.CharField(max_length=150, verbose_name='F.I.O.')),
                ('full_name_uz', models.CharField(max_length=150, null=True, verbose_name='F.I.O.')),
                ('full_name_ru', models.CharField(max_length=150, null=True, verbose_name='F.I.O.')),
                ('full_name_en', models.CharField(max_length=150, null=True, verbose_name='F.I.O.')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True, verbose_name='slug')),
                ('slug_uz', models.SlugField(blank=True, max_length=180, null=True, unique=True, verbose_name='slug')),
                ('slug_ru', models.SlugField(blank=True, max_length=180, null=True, unique=True, verbose_name='slug')),
                ('slug_en', models.SlugField(blank=True, max_length=180, null=True, unique=True, verbose_name='slug')),
                ('specialization', models.CharField(max_length=150, verbose_name='mutaxassislik')),
                ('specialization_uz', models.CharField(max_length=150, null=True, verbose_name='mutaxassislik')),
                ('specialization_ru', models.CharField(max_length=150, null=True, verbose_name='mutaxassislik')),
                ('specialization_en', models.CharField(max_length=150, null=True, verbose_name='mutaxassislik')),
                ('bio', models.TextField(blank=True, verbose_name='tarjimai hol')),
                ('bio_uz', models.TextField(blank=True, null=True, verbose_name='tarjimai hol')),
                ('bio_ru', models.TextField(blank=True, null=True, verbose_name='tarjimai hol')),
                ('bio_en', models.TextField(blank=True, null=True, verbose_name='tarjimai hol')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/', verbose_name='rasm')),
                ('photo_alt', models.CharField(blank=True, max_length=200, verbose_name='rasm alt')),
                ('photo_alt_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='rasm alt')),
                ('photo_alt_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='rasm alt')),
                ('photo_alt_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='rasm alt')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='tajriba (yil)')),
                ('education', models.TextField(blank=True, verbose_name='taʼlim')),
                ('education_uz', models.TextField(blank=True, null=True, verbose_name='taʼlim')),
                ('education_ru', models.TextField(blank=True, null=True, verbose_name='taʼlim')),
                ('education_en', models.TextField(blank=True, null=True, verbose_name='taʼlim')),
                ('certificates', models.TextField(blank=True, verbose_name='sertifikatlar')),
                ('certificates_uz', models.TextField(blank=True, null=True, verbose_name='sertifikatlar')),
                ('certificates_ru', models.TextField(blank=True, null=True, verbose_name='sertifikatlar')),
                ('certificates_en', models.TextField(blank=True, null=True, verbose_name='sertifikatlar')),
                ('languages_spoken', models.CharField(blank=True, max_length=64, verbose_name='tillar')),
                ('is_bookable', models.BooleanField(default=True, verbose_name='qabulga yozish mumkin')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='tartib')),
                ('telegram_username', models.CharField(blank=True, max_length=64, verbose_name='Telegram')),
            ],
            options={
                'verbose_name': 'Shifokor',
                'verbose_name_plural': 'Shifokorlar',
                'ordering': ['order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(verbose_name='hafta kuni')),
                ('start_time', models.TimeField(verbose_name='boshlanish')),
                ('end_time', models.TimeField(verbose_name='tugash')),
                ('slot_minutes', models.PositiveSmallIntegerField(default=30, verbose_name='slot (daq)')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='tanaffus boshi')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='tanaffus oxiri')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='amal qiladi (dan)')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='amal qiladi (gacha)')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='team.doctor', verbose_name='shifokor')),
            ],
            options={
                'verbose_name': 'Shifokor jadvali',
                'verbose_name_plural': 'Shifokor jadvallari',
                'ordering': ['doctor', 'weekday', 'start_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='schedule_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(verbose_name='boshlanish')),
                ('ends_at', models.DateTimeField(verbose_name='tugash')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='sabab')),
                ('reason_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='sabab')),
                ('reason_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='sabab')),
                ('reason_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='sabab')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_off', to='team.doctor', verbose_name='shifokor')),
            ],
            options={
                'verbose_name': 'Dam olish',
                'verbose_name_plural': 'Dam olish vaqtlari',
                'ordering': ['-starts_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='timeoff_end_after_start')],
            },
        ),
    ]
