# Generated by Django 5.2.17 on 2026-08-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='rasm')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='alt matn')),
                ('alt_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='alt matn')),
                ('alt_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='alt matn')),
                ('alt_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='alt matn')),
                ('caption', models.CharField(blank=True, max_length=250, verbose_name='izoh')),
                ('caption_uz', models.CharField(blank=True, max_length=250, null=True, verbose_name='izoh')),
                ('caption_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='izoh')),
                ('caption_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='izoh')),
                ('category', models.CharField(choices=[('clinic', 'Klinika'), ('equipment', 'Uskunalar'), ('team', 'Jamoa'), ('work', 'Ishlarimiz')], default='clinic', max_length=16, verbose_name='kategoriya')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram havolasi')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
            ],
            options={
                'verbose_name': 'Galereya rasmi',
                'verbose_name_plural': 'Galereya',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
