# Generated by Django 5.2.17 on 2026-08-27 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('kind', models.CharField(choices=[('callback', 'Qoʻngʻiroq buyurtmasi'), ('contact', 'Aloqa formasi'), ('price_request', 'Narx soʻrovi'), ('demo_inquiry', 'Demo soʻrovi')], default='callback', max_length=20, verbose_name='turi')),
                ('name', models.CharField(max_length=150, verbose_name='ism')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('message', models.TextField(blank=True, verbose_name='xabar')),
                ('preferred_time', models.CharField(blank=True, max_length=120, verbose_name='qulay vaqt')),
                ('locale', models.CharField(default='uz', max_length=5, verbose_name='til')),
                ('source_page', models.CharField(blank=True, max_length=255, verbose_name='sahifa')),
                ('utm_source', models.CharField(blank=True, max_length=100, verbose_name='utm_source')),
                ('utm_medium', models.CharField(blank=True, max_length=100, verbose_name='utm_medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=100, verbose_name='utm_campaign')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('in_progress', 'Ishlanmoqda'), ('won', 'Yutildi'), ('lost', 'Yoʻqotildi'), ('spam', 'Spam')], db_index=True, default='new', max_length=16, verbose_name='status')),
                ('notified', models.BooleanField(default=False, verbose_name='xabar yuborilgan')),
                ('consent_given_at', models.DateTimeField(blank=True, null=True, verbose_name='rozilik vaqti')),
                ('ip_hash', models.CharField(blank=True, max_length=64, verbose_name='IP hash')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='services.service', verbose_name='xizmat')),
            ],
            options={
                'verbose_name': 'Murojaat',
                'verbose_name_plural': 'Murojaatlar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='leads_lead_status_7559b2_idx')],
            },
        ),
    ]
