# Generated by Django 5.2.17 on 2026-08-27 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('author_name', models.CharField(max_length=150, verbose_name='muallif')),
                ('author_photo', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='rasm')),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='reyting')),
                ('text', models.TextField(verbose_name='sharh')),
                ('text_uz', models.TextField(null=True, verbose_name='sharh')),
                ('text_ru', models.TextField(null=True, verbose_name='sharh')),
                ('text_en', models.TextField(null=True, verbose_name='sharh')),
                ('source', models.CharField(choices=[('manual', 'Qoʻlda'), ('google', 'Google'), ('2gis', '2GIS'), ('yandex', 'Yandex'), ('instagram', 'Instagram')], default='manual', max_length=16, verbose_name='manba')),
                ('source_url', models.URLField(blank=True, verbose_name='manba havolasi')),
                ('reviewed_at', models.DateField(blank=True, null=True, verbose_name='sana')),
                ('is_featured', models.BooleanField(default=False, verbose_name='bosh sahifada')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='tartib')),
            ],
            options={
                'verbose_name': 'Sharh',
                'verbose_name_plural': 'Sharhlar',
                'ordering': ['order', '-reviewed_at'],
            },
        ),
    ]
