/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/appointments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["appointments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appointments/{cancel_token}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["appointments_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appointments/{cancel_token}/cancel/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["appointments_cancel_retrieve"];
        put?: never;
        post: operations["appointments_cancel_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appointments/{cancel_token}/reschedule/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["appointments_reschedule_retrieve"];
        put?: never;
        post: operations["appointments_reschedule_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appointments/form-token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Forma render qilinganda imzolangan token beradi (anti-spam timing tuzogʻi uchun). */
        get: operations["appointments_form_token_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appointments/slots/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["appointments_slots_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Before/After ishlar. Faqat bemor roziligi bor va chop etilganlari. */
        get: operations["cases_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Before/After ishlar. Faqat bemor roziligi bor va chop etilganlari. */
        get: operations["cases_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/doctors/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["doctors_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/doctors/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["doctors_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/faq/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["faq_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/faq/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["faq_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gallery/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["gallery_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gallery/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["gallery_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["leads_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pages/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["pages_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pages/{key}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["pages_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Blog. `?q=` — trigram qidiruv (lotin va kirill uchun). */
        get: operations["posts_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Blog. `?q=` — trigram qidiruv (lotin va kirill uchun). */
        get: operations["posts_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["reviews_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["reviews_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/summary/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Reyting yigʻindisi — sharhlar sahifasi sarlavhasi uchun. */
        get: operations["reviews_summary_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/seo/routes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Sitemap va generateStaticParams uchun bitta manba (T-P3-13).
         *     Har til uchun slug'lar + updated_at. Locale'ga bogʻliq emas, unpaginated.
         */
        get: operations["seo_routes_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Xizmatlar katalogi. `?featured=1` — bosh sahifadagi 6 ta. */
        get: operations["services_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Xizmatlar katalogi. `?featured=1` — bosh sahifadagi 6 ta. */
        get: operations["services_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Xizmatlar katalogi. `?featured=1` — bosh sahifadagi 6 ta. */
        get: operations["services_categories_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/prices/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Narxlar. `prices_visible=False` boʻlsa boʻsh roʻyxat (ADR-004). */
        get: operations["services_prices_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/site-settings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Klinika sozlamalari + ish vaqti + counterlar. Barcha sahifalar uchun. */
        get: operations["site_settings_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AppointmentCreate: {
            doctor?: number | null;
            service: number;
            /** Format: date-time */
            starts_at: string;
            patient_name: string;
            phone: string;
            /**
             * Format: email
             * @default
             */
            email: string;
            /** @default  */
            comment: string;
            /** @default uz */
            locale: components["schemas"]["LocaleEnum"];
            consent: boolean;
            /** @default  */
            consent_text_version: string;
            /** Format: uuid */
            idempotency_key?: string | null;
            /** @default  */
            form_token: string;
            /** @default  */
            referral_note_2: string;
        };
        CasePair: {
            readonly id: number;
            /** Nomi */
            title: string;
            slug?: string;
            readonly alternates: {
                uz?: string;
                ru?: string;
                en?: string;
            };
            /**
             * Yangilangan vaqti
             * Format: date-time
             */
            readonly updated_at: string;
            readonly image_before: {
                /** Format: uri */
                src?: string;
                width?: number | null;
                height?: number | null;
                alt?: string | null;
            } | null;
            readonly image_after: {
                /** Format: uri */
                src?: string;
                width?: number | null;
                height?: number | null;
                alt?: string | null;
            } | null;
            readonly og_image: {
                /** Format: uri */
                src?: string;
                width?: number | null;
                height?: number | null;
                alt?: string | null;
            } | null;
            /** Izoh */
            caption?: string;
            /** Davolash tavsifi */
            treatment_summary?: string;
            /** Davomiyligi */
            duration_note?: string;
            readonly service_slug: string;
            readonly service_title: string;
            readonly doctor_name: string;
            meta_title?: string;
            meta_description?: string;
            /** Bosh sahifada */
            is_featured?: boolean;
            /** Tartib */
            order?: number;
        };
        /**
         * @description * `clinic` - Klinika
         *     * `equipment` - Uskunalar
         *     * `team` - Jamoa
         *     * `work` - Ishlarimiz
         * @enum {string}
         */
        CategoryEnum: "clinic" | "equipment" | "team" | "work";
        ClinicSettings: {
            /** Klinika nomi */
            name?: string;
            /** Shior */
            tagline?: string;
            /** Qisqa taʼrif */
            about_short?: string;
            readonly logo: {
                /** Format: uri */
                src?: string;
                width?: number | null;
                height?: number | null;
                alt?: string | null;
            } | null;
            readonly favicon: {
                /** Format: uri */
                src?: string;
                width?: number | null;
                height?: number | null;
                alt?: string | null;
            } | null;
            readonly hero_image: {
                /** Format: uri */
                src?: string;
                width?: number | null;
                height?: number | null;
                alt?: string | null;
            } | null;
            readonly og_image: {
                /** Format: uri */
                src?: string;
                width?: number | null;
                height?: number | null;
                alt?: string | null;
            } | null;
            readonly theme: {
                brand?: string;
                accent?: string;
                ink?: string;
                surface?: string;
                fontPair?: string;
            };
            /** Asosiy telefon */
            phone_primary?: string;
            /** Qoʻshimcha telefon */
            phone_secondary?: string;
            /** Format: email */
            email?: string;
            telegram_username?: string;
            /**
             * Telegram kanal
             * Format: uri
             */
            telegram_channel_url?: string;
            /**
             * Instagram
             * Format: uri
             */
            instagram_url?: string;
            /**
             * Facebook
             * Format: uri
             */
            facebook_url?: string;
            /**
             * YouTube
             * Format: uri
             */
            youtube_url?: string;
            /** Manzil */
            address?: string;
            /**
             * Kenglik
             * Format: decimal
             */
            map_lat?: string | null;
            /**
             * Uzunlik
             * Format: decimal
             */
            map_lng?: string | null;
            /** Zoom */
            map_zoom?: number;
            /**
             * Yandex Maps
             * Format: uri
             */
            yandex_maps_url?: string;
            /**
             * 2GIS
             * Format: uri
             */
            two_gis_url?: string;
            /** Litsenziya matni */
            license_text?: string;
            /** Yuridik shaxs */
            legal_entity_name?: string;
            /** Narxlar koʻrinsin */
            prices_visible?: boolean;
            /** Onlayn qabul yoqilgan */
            booking_enabled?: boolean;
            default_meta_title?: string;
            default_meta_description?: string;
            /** Yandex Metrika ID */
            metrika_id?: string;
            ga4_id?: string;
            /** Yandex Webmaster */
            yandex_verification?: string;
            google_verification?: string;
            readonly working_hours: components["schemas"]["WorkingHours"][];
            readonly counters: components["schemas"]["StatCounter"][];
        };
        DoctorDetail: {
            readonly id: number;
            /** F.I.O. */
            full_name: string;
            slug?: string;
            readonly alternates: {
                uz?: string;
                ru?: string;
                en?: string;
            };
            /**
             * Yangilangan vaqti
             * Format: date-time
             */
            readonly updated_at: string;
            readonly og_image: {
                /** Format: uri */
                src?: string;
                width?: number | null;
                height?: number | null;
                alt?: string | null;
            } | null;
            /** Mutaxassislik */
            specialization: string;
            readonly photo: {
                /** Format: uri */
                src?: string;
                width?: number | null;
                height?: number | null;
                alt?: string | null;
            } | null;
            /** Rasm alt */
            photo_alt?: string;
            /** Tajriba (yil) */
            experience_years?: number;
            readonly languages: string[];
            /** Qabulga yozish mumkin */
            is_bookable?: boolean;
            /** Tartib */
            order?: number;
            /** Tarjimai hol */
            bio?: string;
            /** Taʼlim */
            education?: string;
            /** Sertifikatlar */
            certificates?: string;
            /** Telegram */
            telegram_username?: string;
            readonly services: Record<string, never>[];
            meta_title?: string;
            meta_description?: string;
        };
        DoctorList: {
            readonly id: number;
            /** F.I.O. */
            full_name: string;
            slug?: string;
            readonly alternates: {
                uz?: string;
                ru?: string;
                en?: string;
            };
            /**
             * Yangilangan vaqti
             * Format: date-time
             */
            readonly updated_at: string;
            readonly og_image: {
                /** Format: uri */
                src?: string;
                width?: number | null;
                height?: number | null;
                alt?: string | null;
            } | null;
            /** Mutaxassislik */
            specialization: string;
            readonly photo: {
                /** Format: uri */
                src?: string;
                width?: number | null;
                height?: number | null;
                alt?: string | null;
            } | null;
            /** Rasm alt */
            photo_alt?: string;
            /** Tajriba (yil) */
            experience_years?: number;
            readonly languages: string[];
            /** Qabulga yozish mumkin */
            is_bookable?: boolean;
            /** Tartib */
            order?: number;
        };
        Faq: {
            readonly id: number;
            /** Savol */
            question: string;
            /** Javob */
            answer: string;
            /** Tartib */
            order?: number;
        };
        GalleryImage: {
            readonly id: number;
            readonly image: {
                /** Format: uri */
                src?: string;
                width?: number | null;
                height?: number | null;
                alt?: string | null;
            } | null;
            /** Alt matn */
            alt?: string;
            /** Izoh */
            caption?: string;
            /** Kategoriya */
            category?: components["schemas"]["CategoryEnum"];
            /**
             * Instagram havolasi
             * Format: uri
             */
            instagram_url?: string;
            /** Tartib */
            order?: number;
        };
        /**
         * @description * `privacy` - Maxfiylik siyosati
         *     * `offer` - Ommaviy oferta
         *     * `terms` - Foydalanish shartlari
         * @enum {string}
         */
        KeyEnum: "privacy" | "offer" | "terms";
        /**
         * @description * `callback` - callback
         *     * `contact` - contact
         *     * `price_request` - price_request
         *     * `demo_inquiry` - demo_inquiry
         * @enum {string}
         */
        KindEnum: "callback" | "contact" | "price_request" | "demo_inquiry";
        LeadCreate: {
            /** @default callback */
            kind: components["schemas"]["KindEnum"];
            name: string;
            phone: string;
            /**
             * Format: email
             * @default
             */
            email: string;
            /** @default  */
            message: string;
            service?: number | null;
            /** @default  */
            preferred_time: string;
            /** @default uz */
            locale: components["schemas"]["LocaleEnum"];
            /** @default  */
            source_page: string;
            /** @default  */
            utm_source: string;
            /** @default  */
            utm_medium: string;
            /** @default  */
            utm_campaign: string;
            consent: boolean;
            /** @default  */
            form_token: string;
            /** @default  */
            referral_note_2: string;
        };
        /**
         * @description * `uz` - uz
         *     * `ru` - ru
         *     * `en` - en
         * @enum {string}
         */
        LocaleEnum: "uz" | "ru" | "en";
        PaginatedCasePairList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null;
            results: components["schemas"]["CasePair"][];
        };
        PaginatedDoctorListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null;
            results: components["schemas"]["DoctorList"][];
        };
        PaginatedGalleryImageList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null;
            results: components["schemas"]["GalleryImage"][];
        };
        PaginatedPostListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null;
            results: components["schemas"]["PostList"][];
        };
        PaginatedPriceItemList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null;
            results: components["schemas"]["PriceItem"][];
        };
        PaginatedReviewList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null;
            results: components["schemas"]["Review"][];
        };
        PaginatedServiceCategoryList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null;
            results: components["schemas"]["ServiceCategory"][];
        };
        PaginatedServiceListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null;
            results: components["schemas"]["ServiceList"][];
        };
        PostDetail: {
            readonly id: number;
            /** Sarlavha */
            title: string;
            slug?: string;
            readonly alternates: {
                uz?: string;
                ru?: string;
                en?: string;
            };
            /**
             * Yangilangan vaqti
             * Format: date-time
             */
            readonly updated_at: string;
            readonly og_image: {
                /** Format: uri */
                src?: string;
                width?: number | null;
                height?: number | null;
                alt?: string | null;
            } | null;
            /** Qisqa matn */
            excerpt?: string;
            readonly cover: {
                /** Format: uri */
                src?: string;
                width?: number | null;
                height?: number | null;
                alt?: string | null;
            } | null;
            readonly author_name: string;
            /**
             * Chop etilgan
             * Format: date-time
             */
            published_at?: string | null;
            /** Oʻqish vaqti (daq) */
            reading_time?: number;
            /** Matn */
            body: string;
            meta_title?: string;
            meta_description?: string;
        };
        PostList: {
            readonly id: number;
            /** Sarlavha */
            title: string;
            slug?: string;
            readonly alternates: {
                uz?: string;
                ru?: string;
                en?: string;
            };
            /**
             * Yangilangan vaqti
             * Format: date-time
             */
            readonly updated_at: string;
            readonly og_image: {
                /** Format: uri */
                src?: string;
                width?: number | null;
                height?: number | null;
                alt?: string | null;
            } | null;
            /** Qisqa matn */
            excerpt?: string;
            readonly cover: {
                /** Format: uri */
                src?: string;
                width?: number | null;
                height?: number | null;
                alt?: string | null;
            } | null;
            readonly author_name: string;
            /**
             * Chop etilgan
             * Format: date-time
             */
            published_at?: string | null;
            /** Oʻqish vaqti (daq) */
            reading_time?: number;
        };
        PriceItem: {
            readonly id: number;
            /** Nomi */
            title: string;
            /**
             * Narx (dan)
             * Format: decimal
             */
            price_from: string;
            /**
             * Narx (gacha)
             * Format: decimal
             */
            price_to?: string | null;
            /** Valyuta */
            currency?: string;
            /** Birlik */
            unit?: string;
            /** Izoh */
            qualifier?: string;
            /** Aksiya */
            is_promo?: boolean;
            /** Aksiya izohi */
            promo_note?: string;
            readonly category_slug: string;
            readonly service_slug: string;
            /** Tartib */
            order?: number;
        };
        Review: {
            readonly id: number;
            /** Muallif */
            author_name: string;
            readonly author_photo: {
                /** Format: uri */
                src?: string;
                width?: number | null;
                height?: number | null;
                alt?: string | null;
            } | null;
            /** Reyting */
            rating?: number;
            /** Sharh */
            text: string;
            /** Manba */
            source?: components["schemas"]["SourceEnum"];
            /**
             * Manba havolasi
             * Format: uri
             */
            source_url?: string;
            /**
             * Sana
             * Format: date
             */
            reviewed_at?: string | null;
            /** Bosh sahifada */
            is_featured?: boolean;
            /** Tartib */
            order?: number;
        };
        ServiceCategory: {
            readonly id: number;
            /** Nomi */
            title: string;
            slug?: string;
            icon?: string;
            /** Tartib */
            order?: number;
        };
        ServiceDetail: {
            readonly id: number;
            /** Nomi */
            title: string;
            slug?: string;
            readonly alternates: {
                uz?: string;
                ru?: string;
                en?: string;
            };
            /**
             * Yangilangan vaqti
             * Format: date-time
             */
            readonly updated_at: string;
            readonly og_image: {
                /** Format: uri */
                src?: string;
                width?: number | null;
                height?: number | null;
                alt?: string | null;
            } | null;
            /** Qisqa tavsif */
            excerpt?: string;
            icon?: string;
            readonly cover: {
                /** Format: uri */
                src?: string;
                width?: number | null;
                height?: number | null;
                alt?: string | null;
            } | null;
            /** Davomiyligi (daq) */
            duration_minutes?: number;
            /** Bosh sahifada */
            is_featured?: boolean;
            readonly category: components["schemas"]["ServiceCategory"];
            /** Tartib */
            order?: number;
            /** Toʻliq tavsif */
            body?: string;
            readonly prices: components["schemas"]["PriceItem"][];
            readonly faqs: components["schemas"]["Faq"][];
            readonly doctors: Record<string, never>[];
            meta_title?: string;
            meta_description?: string;
        };
        ServiceList: {
            readonly id: number;
            /** Nomi */
            title: string;
            slug?: string;
            readonly alternates: {
                uz?: string;
                ru?: string;
                en?: string;
            };
            /**
             * Yangilangan vaqti
             * Format: date-time
             */
            readonly updated_at: string;
            readonly og_image: {
                /** Format: uri */
                src?: string;
                width?: number | null;
                height?: number | null;
                alt?: string | null;
            } | null;
            /** Qisqa tavsif */
            excerpt?: string;
            icon?: string;
            readonly cover: {
                /** Format: uri */
                src?: string;
                width?: number | null;
                height?: number | null;
                alt?: string | null;
            } | null;
            /** Davomiyligi (daq) */
            duration_minutes?: number;
            /** Bosh sahifada */
            is_featured?: boolean;
            readonly category: components["schemas"]["ServiceCategory"];
            /** Tartib */
            order?: number;
        };
        /**
         * @description * `manual` - Qoʻlda
         *     * `google` - Google
         *     * `2gis` - 2GIS
         *     * `yandex` - Yandex
         *     * `instagram` - Instagram
         * @enum {string}
         */
        SourceEnum: "manual" | "google" | "2gis" | "yandex" | "instagram";
        StatCounter: {
            readonly id: number;
            /** Nom */
            label: string;
            /** Qiymat */
            value: number;
            /** Qoʻshimcha */
            suffix?: string;
            icon?: string;
            /** Tartib */
            order?: number;
        };
        StaticPage: {
            /** Kalit */
            key: components["schemas"]["KeyEnum"];
            /** Sarlavha */
            title: string;
            /** Matn */
            body: string;
            meta_title?: string;
            meta_description?: string;
        };
        /**
         * @description * `0` - Dushanba
         *     * `1` - Seshanba
         *     * `2` - Chorshanba
         *     * `3` - Payshanba
         *     * `4` - Juma
         *     * `5` - Shanba
         *     * `6` - Yakshanba
         * @enum {integer}
         */
        WeekdayEnum: 0 | 1 | 2 | 3 | 4 | 5 | 6;
        WorkingHours: {
            /** Hafta kuni */
            weekday: components["schemas"]["WeekdayEnum"];
            readonly weekday_display: string;
            /**
             * Ochilish
             * Format: time
             */
            opens?: string | null;
            /**
             * Yopilish
             * Format: time
             */
            closes?: string | null;
            /** Dam olish kuni */
            is_closed?: boolean;
            /** Izoh */
            note?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    appointments_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppointmentCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["AppointmentCreate"];
                "multipart/form-data": components["schemas"]["AppointmentCreate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    appointments_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cancel_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    appointments_cancel_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cancel_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    appointments_cancel_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cancel_token: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
                "application/x-www-form-urlencoded": {
                    [key: string]: unknown;
                };
                "multipart/form-data": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    appointments_reschedule_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cancel_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    appointments_reschedule_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cancel_token: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
                "application/x-www-form-urlencoded": {
                    [key: string]: unknown;
                };
                "multipart/form-data": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    appointments_form_token_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    appointments_slots_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    cases_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCasePairList"];
                };
            };
        };
    };
    cases_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CasePair"];
                };
            };
        };
    };
    doctors_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDoctorListList"];
                };
            };
        };
    };
    doctors_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorDetail"];
                };
            };
        };
    };
    faq_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Faq"][];
                };
            };
        };
    };
    faq_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this FAQ. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Faq"];
                };
            };
        };
    };
    gallery_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedGalleryImageList"];
                };
            };
        };
    };
    gallery_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Galereya rasmi. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GalleryImage"];
                };
            };
        };
    };
    leads_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["LeadCreate"];
                "multipart/form-data": components["schemas"]["LeadCreate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    pages_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaticPage"][];
                };
            };
        };
    };
    pages_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: "privacy" | "offer" | "terms";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaticPage"];
                };
            };
        };
    };
    posts_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPostListList"];
                };
            };
        };
    };
    posts_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostDetail"];
                };
            };
        };
    };
    reviews_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedReviewList"];
                };
            };
        };
    };
    reviews_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Sharh. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Review"];
                };
            };
        };
    };
    reviews_summary_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Review"];
                };
            };
        };
    };
    seo_routes_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    services_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedServiceListList"];
                };
            };
        };
    };
    services_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceDetail"];
                };
            };
        };
    };
    services_categories_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedServiceCategoryList"];
                };
            };
        };
    };
    services_prices_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPriceItemList"];
                };
            };
        };
    };
    site_settings_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClinicSettings"];
                };
            };
        };
    };
}
